### ISSUE TITLE
can't install the extension

### ISSUE THREAD

**Issue by Issam-seghir** [lunapaint/vscode-luna-paint#170]
System : windows 10 pro  Version 21H2
Vscode : 1.75.0

```
Error while installing 'Luna Paint — Image Editor' extension. 
Please check the [log](command:workbench.action.showWindowLog) for more details.
```

```log
2023-02-28 12:20:44.866 [error] Signature: PackageIntegrityCheckFailed
    at yt.download (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:62:17985)
    at async $.h (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:171351)
2023-02-28 12:20:44.899 [error] PackageIntegrityCheckFailed: Signature: PackageIntegrityCheckFailed
    at yt.download (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:62:17985)
    at async $.h (vscode-file://vscode-app/c:/Users/user/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:90:171351)
```

when trying to download manually

![image](https://user-images.githubusercontent.com/74573675/221839694-aa6a6b80-64d9-435d-ac47-dea33c1ddf25.png)

```log

الثلاثاء 28-فيفرييه-2023 12:21:56 م - Microsoft VSIX Installer
الثلاثاء 28-فيفرييه-2023 12:21:56 م - -------------------------------------------
الثلاثاء 28-فيفرييه-2023 12:21:56 م - vsixinstaller.exe version:
الثلاثاء 28-فيفرييه-2023 12:21:56 م - 16.11.57
الثلاثاء 28-فيفرييه-2023 12:21:56 م - -------------------------------------------
الثلاثاء 28-فيفرييه-2023 12:21:56 م - Command line parameters:
الثلاثاء 28-فيفرييه-2023 12:21:56 م - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\GAMING\Downloads\Tyriar.luna-paint-0.16.0.vsix
الثلاثاء 28-فيفرييه-2023 12:21:56 م - -------------------------------------------
الثلاثاء 28-فيفرييه-2023 12:21:56 م - Microsoft VSIX Installer
الثلاثاء 28-فيفرييه-2023 12:21:56 م - -------------------------------------------
الثلاثاء 28-فيفرييه-2023 12:21:57 م - Skipping product Microsoft.VisualStudio.Product.BuildTools (94e45a98) since it does not support extensions
الثلاثاء 28-فيفرييه-2023 12:21:57 م - Initializing Install...
الثلاثاء 28-فيفرييه-2023 12:21:57 م - Extension Details...
الثلاثاء 28-فيفرييه-2023 12:21:57 م - 	Identifier         : luna-paint
الثلاثاء 28-فيفرييه-2023 12:21:57 م - 	Name               : Luna Paint — Image Editor
الثلاثاء 28-فيفرييه-2023 12:21:57 م - 	Author             : Tyriar
الثلاثاء 28-فيفرييه-2023 12:21:57 م - 	Version            : 0.16.0
الثلاثاء 28-فيفرييه-2023 12:21:57 م - 	Description        : Edit images in VS Code! Supports png, jpg, webp, bmp, tga and ico formats.
الثلاثاء 28-فيفرييه-2023 12:21:57 م - 	Locale             : en-US
الثلاثاء 28-فيفرييه-2023 12:21:57 م - 	MoreInfoURL        : 
الثلاثاء 28-فيفرييه-2023 12:21:57 م - 	InstalledByMSI     : False
الثلاثاء 28-فيفرييه-2023 12:21:57 م - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
الثلاثاء 28-فيفرييه-2023 12:21:57 م - 
الثلاثاء 28-فيفرييه-2023 12:21:58 م - 	SignatureState     : Unsigned
الثلاثاء 28-فيفرييه-2023 12:21:58 م - 	Supported Products : 
الثلاثاء 28-فيفرييه-2023 12:21:58 م - 		Microsoft.VisualStudio.Code
الثلاثاء 28-فيفرييه-2023 12:21:58 م - 			Version : 
الثلاثاء 28-فيفرييه-2023 12:21:58 م - 
الثلاثاء 28-فيفرييه-2023 12:21:58 م - 	References         : 
الثلاثاء 28-فيفرييه-2023 12:21:58 م - Signature Details...
الثلاثاء 28-فيفرييه-2023 12:21:58 م - 	Extension is not signed.
الثلاثاء 28-فيفرييه-2023 12:21:58 م - 
الثلاثاء 28-فيفرييه-2023 12:21:58 م - Searching for applicable products...
الثلاثاء 28-فيفرييه-2023 12:21:58 م - Found installed product - Global Location
الثلاثاء 28-فيفرييه-2023 12:21:58 م - VSIXInstaller.NoApplicableSKUsException: One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by Tyriar** [comment]
I don't think this is an issue with the extension, you should report to the vscode repo: https://github.com/microsoft/vscode/issues/new/choose
